### ISSUE TITLE
[Feature] "Block" draft support to the custom card list format

### ISSUE THREAD

**Issue by sprangg** [Senryoku/Draftmancer#377]
It'd be cool to be able to do a block draft with the custom card list format, i.e. a draft where the packs would be from different custom sets or cubes.

To do this, it'd need to be possible to specify different layouts for packs 1, 2 and 3. And of course a 4+ pack draft should support this as well... So if this method is used the layouts should be checked before the draft, to make sure the number of packs there matches the number used for the draft.

**Comment by Senryoku** [comment]
Sorry for the delay, figuring out how I wanted to tackle this was tricky!

I'm considering adding a `[Settings]` section containing a JSON object to the format.
Hopefully it will ultimately supersede the `[Layouts]` section (although it still supported for now).
This issue is addressed by the addition of the `predeterminedLayouts` setting (the list will wrap around if it's shorter than the number of generated boosters).
#378 will also be fixed by the `layoutWithReplacement` setting (I'm closing the other issue to concentrate the discussion about the file format here).

I'm working on a prototype in #418. Since some parts are finicky and the change is substantial, I've deployed a temporary test instance accessible here:
https://mtgadraft.cf/
You can find a description of the new format at https://mtgadraft.cf/cubeformat.html
If you want to quickly try the changes, you can use the example test file at https://github.com/Senryoku/MTGADraft/blob/ab96999b77be626e03639cc09f1b1df9060d077b/test/data/PredeterminedLayouts.txt

Please let me know if you have any feedback on this!

As I'm writing this I'm realizing that you'd probably want to be able to specify multiple layouts for each pack, maybe even overriding the weights... I'll have to think about that :D

**Comment by sprangg** [comment]
Cool stuff! Indeed ```layoutWithReplacement``` would allow to do a chaos draft with packs from multiple sets/cubes, and ```predeterminedLayouts``` would allow to do a block draft.

The only downside to these both would, afaik, be that they don't really support different layouts for the different cubes/sets, for example the mythic rarity in a custom set.

If using the mythic rarity layout (7 packs of a set having a rare and 1 having a mythic), the chaos draft would almost certainly not have the same amount of the different sets.

And in a block draft, the amount of packs with mythics opened would need to be predetermined.

But even if the system is not perfect, seems already nice! Mythics are something that we can live without.

**Comment by Senryoku** [comment]
For more flexibility with the block drafts, I'm thinking about adding these syntax:
```
predeterminedLayouts: [["Set1_Rare", "Set1_Mythic"], ["Set2_Rare", "Set2_Mythic"]]
```
Each booster now has a corresponding array of possible layouts, with weights taken from the layout declaration.
```
predeterminedLayouts: [{"Set1_Rare": 7, "Set1_Mythic": 1}, {"Set2_Rare": 7, "Set2_Mythic": 1}]
```
Same thing, but this way you can override layout weights.


I don't have a great fix for chaos drafts. To address it properly we'd need a way to group layouts like proposed for `predeterminedLayouts`. I'm sure what that looks like.

**Comment by Senryoku** [comment]
cfdb4cfbe118e418ba927fa23f124c4d410cb86c
