### ISSUE TITLE
Uniformize start dialogs

### ISSUE THREAD

**Issue by Senryoku** [Senryoku/Draftmancer#541]
Start game dialogs uses either a custom component or a sweetalert, leading to disparate styles.
We could also share more CSS between these custom components (mostly around settings).

 - Convert dialogs using sweetalert to custom components.
   - [x] Winston (ba53248)
   - [x] Winchester
   - [x] Grid
   - [x] Glimpse/Burn
   - [x] Minesweeper (c4a95bd)
 - Extract common CSS and use it everywhere.

**Comment by tooomm** [comment]
I like the reset buttons you put to all dialogs and that they are now styled identical.
The minesweaper dialog is also fixed for me. 👍 

<br>

Though, the font issue from https://github.com/Senryoku/Draftmancer/issues/539 is now persistent across all dialogs since they are all custom components now.
- old:
  <img width="465" alt="image" src="https://github.com/Senryoku/Draftmancer/assets/9874850/e6353a1b-5fb8-439a-8f5d-ecd7952189b7">
- new:
  ![image](https://github.com/Senryoku/Draftmancer/assets/9874850/d24eb4b5-77a7-4515-9b68-2e334a081021)
  There is also a scrollbar visible on the side now. :)

Both of these issues are still an Edge only issue for me. On Firefox, the font looks better (same old one from before) and there is no scrollbar:
![image](https://github.com/Senryoku/Draftmancer/assets/9874850/1d218d24-72c2-47d5-a784-ec6ecd98c485)

**Comment by Senryoku** [comment]
Ah, the font issue was Edge specific, that makes more sense! Just committed a fix for that.
No clue why the scrollbar behavior differs though.
