### ISSUE TITLE
add secret lair?

### ISSUE THREAD

**Issue by fluidvanadium** [Senryoku/Draftmancer#603]

**Comment by Senryoku** [comment]
Which one?
I plan on deploying the next update after Ixalan is fully spoiled, any missing Secret Lair cards should be added then.

**Comment by fluidvanadium** [comment]
all of them! i like the expanded universe stuff

**Comment by Senryoku** [comment]
Just deployed an update.
Is there any specific SLD cards missing right now?

**Comment by fluidvanadium** [comment]
oh, maybe by deselecting all packs and using all cards?
im trying to add all black-bordered prints but not have unfinity or alchemy

**Comment by fluidvanadium** [comment]
im hoping to find a Glenn one day

**Comment by Senryoku** [comment]
> oh, maybe by deselecting all packs and using all cards?

Oh, I see. Yes, since they're not part of a draftable set, it's the only way to open them using the set selector. 

However, all the secret lair cards should be supported, meaning you can add them to a cube. "Glenn, the Voice of Calm" for example can be imported using its in-universe name and the set code: `Gregor, Shrewd Magistrate (SLD)`

**Comment by Senryoku** [comment]
Secret Lair cards should be available for cubes, tell me if I'm missing something.

Closing this for now.
