### ISSUE TITLE
Allow imports from CubeCobra .txt export

### ISSUE THREAD

**Issue by griffinclark** [Senryoku/Draftmancer#761]
When a cube is exported from CubeCobra, the text file always contains "# mainboard" and "# maybeboard". Please automatically parse these, throwing out the maybeboard and automatically removing the mainboard tag. Thanks!

**Comment by Senryoku** [comment]
Importing directly from Cube Cobra works fine in my experience.
Is there a reason why you're exporting from Cube Cobra to a text file then importing it rather than using the direct import feature?

The uploaded cube files are supposed to be in the Draftmancer format. It's possible I could change it to accommodate this use case, but I'd rather avoid this kind of special cases as much as possible.

**Comment by Senryoku** [comment]
#767 adds support for `#` comments and treats `# maybeboard` as a special case, ignoring the rest of the file.
